=== dawidh15/etl_python/schema/table_schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "table_name": {
            "type": "string"
        },
        "PK": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "Type 1": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "Type 2": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "Type 3": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    },
    "required": [
        "PK",
        "Type 1",
        "Type 2",
        "Type 3",
        "table_name"
    ]
}

=== dawidh15/etl_python/data/table_1_definition.json
{
    "table_name": "My Table",
    "PK": [["PK_COL_1", "number"],["PK_COL_2", "number"],["PK_COL_3", "string"] ],
    "Type 1": [["T1_1", "number"],["T1_2", "number"],["T1_3", "string"] ],
    "Type 2": [["T2_1", "number"],["T2_2", "number"],["T2_3", "string"] ],
    "Type 3": [["T3_1", "number"],["T3_2", "number"],["T3_3", "string"] ] 
}
